import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const PLATFORM_NAME = process.env.PLATFORM_NAME || 'SiteAnalyzer Pro';
const SIGNUP_URL = process.env.SIGNUP_URL || 'https://siteanalyzer.pro';

export interface LeadDiscoveryParams {
  category: string;
  state: string;
  city: string;
  ratingCeiling?: number;
  minReviews?: number;
  maxResults?: number;
}

function buildLeadDiscoveryPrompt(p: Required<LeadDiscoveryParams>): string {
  return `You are an expert business intelligence analyst and lead generation specialist.
Your task: find real ${p.category} businesses in ${p.city}, ${p.state} that have low public ratings and are struggling online.

SEARCH INSTRUCTIONS
Use web_search with these queries to find real businesses:
1. Search: "${p.category} ${p.city} ${p.state} yelp 1 star 2 star 3 star low rating"
2. Search: "site:yelp.com ${p.category} ${p.city} poor reviews"
3. Search: "${p.category} ${p.city} ${p.state} google reviews 2 stars 3 stars"
4. Search: "worst ${p.category} ${p.city} ${p.state} reviews complaints"

TARGET CRITERIA
- Rating: 1.0 to ${p.ratingCeiling} stars on Yelp OR Google OR TripAdvisor OR BBB
- Minimum reviews: ${p.minReviews} (skip sparse/spam listings)
- Must have ANY online presence: website, Yelp page, or Google Business profile
- Return up to ${p.maxResults} businesses total
- Include the business even if you cannot find an email — set email: null

FOR EACH BUSINESS
After web search, collect:
- businessName, subCategory (specific type e.g. "Italian Restaurant"), rating, reviewCount
- ratingTrend: compare last 5 reviews vs overall — "declining" | "flat" | "improving"
- reviewResponseRate: estimate % of reviews owner has responded to
- primarySource: where you found the rating (Yelp/Google/TripAdvisor/BBB/Other)
- address, city, state (2-letter), zipCode, phone, website (if any)
- email: crawl their website /contact and /about pages for mailto: links or email addresses; if none found set null
- ownerName: if publicly listed on website or BBB, else null
- contactFound: true if email found
- hasOnlineOrdering: true/false (e.g. on DoorDash, Uber Eats, their own site)
- hasSocialMedia: true/false (any active Facebook/Instagram)
- lastReviewDate: most recent review date as YYYY-MM-DD

FIND 2-3 LOCAL COMPETITORS WHO ARE OUTPERFORMING THEM (rating 4.0+):
- name, rating, reviewCount, keyAdvantage (one specific sentence: what do they do better?)

GENERATE 3 TEASER FINDINGS (specific to this business, ends with "..."):
Choose the 3 most alarming from:
  T1 - Rating declining (show actual numbers from recent vs overall reviews)
  T2 - Named competitor pulling customers away
  T3 - Missing delivery/sales channel (DoorDash, Uber Eats, online ordering)
  T4 - Review response rate vs local average
  T5 - Repeated complaint theme in negative reviews with no owner response
  T6 - Website quality gap (no menu, no online ordering, broken pages)
  T7 - Social media silence vs active competitor
  T8 - Off-peak revenue opportunity competitors capture

GENERATE TEASER REPORT COPY:
- emailSubject: "[businessName] — we found 3 things hurting your rating in ${p.city}"
- emailSubjectVariant: "Why [businessName] is losing customers to [top competitor]"
- openingHook: 2 personalised sentences referencing their actual rating + a named local competitor
- ctaHeadline: "Get your complete competitive analysis"
- ctaBody: "See all 12 findings, your personalised 90-day growth roadmap, and the exact steps your top competitors are using to outrank you."
- ctaButtonText: "Get your full report — $99 →"
- ctaUrl: "${SIGNUP_URL}?src=teaser&city=${p.city}&cat=${encodeURIComponent(p.category)}"
- footerText: "Generated by ${PLATFORM_NAME} · Based on publicly available review data · To unsubscribe, reply STOP."

CONVERSION SCORE (1–10):
+3 if rating ≤ 2.5 stars
+2 if email found
+2 if rating is declining
+1 if has a website
+1 if has social media
+1 if reviewCount > 50

Sort businesses by conversionScore descending.

OUTPUT FORMAT — return ONLY valid JSON, no markdown, start with { end with }:

{
  "queryMeta": {
    "category": "${p.category}",
    "state": "${p.state}",
    "city": "${p.city}",
    "ratingCeiling": ${p.ratingCeiling},
    "minReviews": ${p.minReviews},
    "maxResults": ${p.maxResults},
    "totalFound": 0,
    "contactFoundCount": 0,
    "avgRating": 0.0,
    "generatedAt": "ISO date string"
  },
  "businesses": [
    {
      "businessName": "string",
      "category": "${p.category}",
      "subCategory": "string",
      "rating": 2.8,
      "reviewCount": 47,
      "ratingTrend": "declining",
      "reviewResponseRate": "0%",
      "primarySource": "Yelp",
      "address": "string",
      "city": "${p.city}",
      "state": "XX",
      "zipCode": "string or null",
      "phone": "string or null",
      "website": "https://... or null",
      "email": "owner@business.com or null",
      "ownerName": "string or null",
      "contactFound": false,
      "hasOnlineOrdering": false,
      "hasSocialMedia": false,
      "lastReviewDate": "YYYY-MM-DD",
      "conversionScore": 8,
      "competitors": [
        { "name": "string", "rating": 4.3, "reviewCount": 210, "keyAdvantage": "one specific sentence" }
      ],
      "teaserFindings": [
        { "code": "T1", "title": "string", "finding": "specific finding ending with ..." },
        { "code": "T2", "title": "string", "finding": "specific finding ending with ..." },
        { "code": "T3", "title": "string", "finding": "specific finding ending with ..." }
      ],
      "teaserReport": {
        "emailSubject": "string",
        "emailSubjectVariant": "string",
        "openingHook": "string",
        "ctaHeadline": "Get your complete competitive analysis",
        "ctaBody": "string",
        "ctaButtonText": "Get your full report — $99 →",
        "ctaUrl": "string",
        "footerText": "string"
      }
    }
  ]
}`;
}

export async function runLeadDiscovery(params: LeadDiscoveryParams): Promise<Record<string, unknown>> {
  const fullParams: Required<LeadDiscoveryParams> = {
    category: params.category,
    state: params.state,
    city: params.city,
    ratingCeiling: params.ratingCeiling ?? 3.5,
    minReviews: params.minReviews ?? 3,
    maxResults: params.maxResults ?? 10,
  };

  const prompt = buildLeadDiscoveryPrompt(fullParams);

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 16000,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    tools: [{ type: 'web_search_20250305', name: 'web_search' }] as any,
    messages: [{ role: 'user', content: prompt }],
  });

  console.log('[leads] stop_reason:', response.stop_reason, 'blocks:', response.content.length);

  let result: Record<string, unknown> | null = null;
  for (const block of response.content) {
    if (block.type === 'text') {
      console.log('[leads] text block length:', block.text.length);
      const match = block.text.match(/\{[\s\S]*\}/);
      if (match) {
        try {
          result = JSON.parse(match[0]);
          break;
        } catch (parseErr) {
          console.error('[leads] JSON parse failed, preview:', match[0].slice(0, 500));
        }
      } else {
        console.error('[leads] no JSON in block, preview:', block.text.slice(0, 300));
      }
    }
  }

  if (!result) {
    return {
      queryMeta: {
        category: fullParams.category,
        state: fullParams.state,
        city: fullParams.city,
        ratingCeiling: fullParams.ratingCeiling,
        minReviews: fullParams.minReviews,
        maxResults: fullParams.maxResults,
        totalFound: 0,
        contactFoundCount: 0,
        avgRating: 0,
        generatedAt: new Date().toISOString(),
      },
      businesses: [],
    };
  }

  return result;
}
